### ISSUE TITLE
Reverse result passcode not working 

### ISSUE THREAD

**Issue by TheCodesterr** [jakeajames/TimeToUnlock#1]
For example, if it’s 9:02 and this option is selected I will enter 2090 and it does not work. 

Running 11.3.1 on iPhone 6.

**Comment by jakeajames** [comment]
I'm looking into it

Il giovedì 23 agosto 2018, TheCodesterr <notifications@github.com> ha
scritto:

**Comment by TheCodesterr** [comment]
Cool and I also think it kicks you off WiFi

On Aug 26, 2018, at 12:09 PM, Jake James <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm looking into it

Il giovedì 23 agosto 2018, TheCodesterr <notifications@github.com<mailto:notifications@github.com>> ha
scritto:

**Comment by jakeajames** [comment]
Pushed new version to BigBoss. Wait for them to update it.

Il domenica 26 agosto 2018, TheCodesterr <notifications@github.com> ha
scritto:

> Cool and I also think it kicks you off WiFi
>
> On Aug 26, 2018, at 12:09 PM, Jake James <notifications@github.com<mailto:
