### ISSUE TITLE
Error loading Preference bundle

### ISSUE THREAD

**Issue by TrueSlavaGopnik** [jakeajames/TimeToUnlock#5]
I have a a12 device iOS 12.4 version and I can’t get Timetounlock running. Maybe itimetounlock is not compatible with my device, but I have found no answers to that question

**Comment by jakeajames** [comment]
What does it do? An error? A crash?

Il giorno venerdì 17 aprile 2020, TrueSlavaGopnik <notifications@github.com>
ha scritto:

**Comment by TrueSlavaGopnik** [comment]
It says ”There was an error loading preference bundle for TimeToUnlock” in settings
